						<!-- featured band module --><tr>
							<td>
								<table border="0" cellspacing="0" cellpadding="0" width="600" align="center" style="background:#121212; padding:0px; margin:0; ">
									<tr>
										<td width="600" height="224">
											<img border="0" src="http://www.oxx.ch/images/[EVENTIMAGE]" width="600" height="225" style="width:600px; height:225px;" alt="[TITLE]">
										</td>
									</tr>
									<tr style="text-align:left">
										<td width="600">
											<table border="0" cellspacing="0" width="600" cellpadding="20" align="left" style="margin:0;"><tr>
													<td width="600" style="padding:20px;">
														<table border="0" cellspacing="0" width="560" align="left" style="padding:0; margin:0;">
															<tr>
																<td>
																	<h1 style="margin:0; padding:0;font-size:0px; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif; color:#FFFFFF; font-weight:700;"><span style="font-size:35px; letter-spacing:-.03em; line-height:1.1;">[TITLE]</span></h1>
																</td>
															</tr>
															<tr>
																<td width="560" height="5">
																	<!-- space -->
																</td>
															</tr>
															<tr>
																<td>
																	<h3 style="padding:0; margin:0; color:#FFFFFF; font-weight:500; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:0px;"><span style="font-size:18px; letter-spacing:-.03em; line-height:1.3;">[SUBTITLE]</span></h3>
																</td>
															</tr>
															<tr>
																<td width="560" height="5">
																	<!-- space -->
																</td>
															</tr>
															<tr>
																<td>
																	<p style="margin:0; color:#A6A6A6; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif; padding:0; font-size:0px; line-height:20px;"><span style="font-size:14px; letter-spacing:-.02em; line-height:20px;">[EVENTDESCRIPTION]</span></p>
																</td>
															</tr>
															<tr>
																<td width="600" height="17" style="height:17px;">
																	<!-- space -->
																</td>
															</tr>
															<tr style="text-align:left;">
																<td width="560" valign="top">
																	<table border="0" cellspacing="0" cellpadding="0" width="560" height="40" align="left" style="background:#3D93D6; padding:0; margin:0;"><tr style="text-align:center;">
																			<td style="width:560px; height:40px;" valign="middle">
																				<a href="[EVENTURL]" style="padding:10px 25px; background-color:#3D93D6; vertical-align: middle; text-align:center; text-decoration:none; color:#ffffff; font-weight:700; font-size:16px; border:none; margin:0; line-height:20px; display:inline-block;"><img border="0" src="play.gif" width="12" height="14" style="height:14px; width:12px;"> [EVENTDATE] <span style="font-weight: normal;">&nbsp;&nbsp;&nbsp;[EVENTDOORS]</span></a>
																			</td>
																		</tr>
																	</table>
																</td>
															</tr>
														</table>
													</td>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<!-- // featured band module --><tr>
							<td width="600" height="20">
								 
							</td>
						</tr>
