						<!-- // Do you have what it takes? --><!-- footer --><tr>
							<td align="center">
								<table bgcolor="#252525" border="0" cellspacing="0" cellpadding="0" width="600" align="center" height="80" style="background-color:#252525; height:80px;"><tr style="text-align:center;">
										<td height="80" style="color:#B2B2B2; font-size:11px; line-height:22px;">
											<a href="[UNSUBSCRIBEURL]" style="color:#B2B2B2; text-decoration:none; font-weight:700;">Unsubscribe</a>
											 | 
											<a href="http://www.oxx.ch" style="color:#B2B2B2; text-decoration:none; font-weight:700;">Privacy Policy</a>
											<br>
											OX. Kultur im Ochsen &nbsp;|&nbsp; Ochsengasse 2 &nbsp;|&nbsp; 4800 Zofingen &nbsp;|&nbsp; <a href="http://www.oxx.ch" style="color:#B2B2B2; text-decoration:none;">www.oxx.ch</a></td>
									</tr></table>
							</td>
						</tr>
						<!-- // footer -->
					</table>
					<!-- // main table -->
				</td>
			</tr></table>
		<!-- // center -->
	</body>
</html>